### ISSUE TITLE
AppleALC source code

### ISSUE THREAD

**Issue by cowpod** [leon0410898/OC-XPS13-9300#19]
Hey,
Is it possible for the AppleALC source for layout 93 to be uploaded? 
AppleALC is currently at 1.5.5, so I'd like to be able to update it when possible.
I have tried recreating the layouts, however I can't get the Speakers to work. 
3-23, 2-33, 7-36-18, 8-35-25
Using the same verbs from the kext Info.plist.

**Comment by leon0410898** [comment]
I'm not sure this is the latest or not.
https://drive.google.com/file/d/16v9xB6A2GDS-G7Pj8LgC3hqvnkuCG2iJ/view?usp=sharing

**Comment by leon0410898** [comment]
here are some pictures. I hope this may help you.
![IMG_7432](https://user-images.githubusercontent.com/32150891/102694347-5f1b1680-425b-11eb-870b-d657afb694bd.JPG)
![IMG_7441](https://user-images.githubusercontent.com/32150891/102694349-60e4da00-425b-11eb-960b-71d64062f3c7.JPG)

**Comment by najeebanwer** [comment]
@leon0410898 thanks a lot; the information you have posted in this repository has been a great help to me.
Can you please send your latest changes for AppleALC/layout-id=93 as a pull request to the maintainers of AppleALC so that it becomes a part of the official releases?

**Comment by najeebanwer** [comment]
The latest version of AppleALC (1.5.5) has changes to Controllers.plist for "Icelake Smart Sound Technology Audio Controller" that cause my laptop to freeze right after boot. All I have to do is set the layout-id to one of the existing layout-id (e.g. 11) and my laptop freezes with both the internal and external display blank. If I set the layout-id to an invalid value (e.g. 93, because it is not included in the release) then the system works fine.
Please let me know if you get the audio working with the latest Lilu & AppleALC. I have given up on AppleALC for now and I am using VoodooHDA. It works fine for the speakers and microphone, but the headphone output is very distorted.

**Comment by cowpod** [comment]
I've got 1.5.5 working with my own pathmap+verbs. Still can't get LineIn to work, and the headphones are scratchy without additional verbs; but this seems to be quite normal for dell laptops! I'll push it to acidanthera/AppleALC when I can.
@leon0410898, do you possibly have the source for ComboJack, or the verbs that it sends?

**Comment by leon0410898** [comment]
> @leon0410898 thanks a lot; the information you have posted in this repository has been a great help to me.
> Can you please send your latest changes for AppleALC/layout-id=93 as a pull request to the maintainers of AppleALC so that it becomes a part of the official releases?

Due to work need, i've changed my OS to linux and not work on hackintosh recently. I'll ask my friend to send the pull request to the maintainers. I wounder if there are any problems with current applealc and ComboJack? I've tested before and they are fully worked on my laptop. Speaker, microphone and headphone both work fine. There is  no distortion even if i used my low-impedance earphones.

**Comment by cowpod** [comment]
Hey, there aren't any issues at the moment. But for future compatibility it would be best to have the ComboJack verbs/source available to update- much like updating AppleALC in the future.

**Comment by najeebanwer** [comment]
There is a pull request which has not been merged yet in the AppleALC website "add Realtek ALC289 layoutid99 for Dell XPS 13 9300 by DalianSky."

**Comment by cowpod** [comment]
Great thanks! Found the pull you mentioned; https://github.com/acidanthera/AppleALC/pull/647
